FlaskApp/posts/routes.py
from flask import render_template, redirect, url_for, flash, Blueprint
from FlaskApp import db, mail
from FlaskApp.models import User, Post
from FlaskApp.posts.forms import PostForm
from flask_login import current_user, login_required
from flask_mail import Message
from datetime import datetime


posts = Blueprint('posts', __name__)


@posts.route('/<string:team>/posts/<int:post_id>')
@login_required
def post_page(team, post_id):
    # posts pages are on a per-team basis eg Team1 cannot view posts of Team2
    # check that the current user's team is the same as the team associated
    # with the posts
    if current_user.team != team:
        flash("You must be a player on this team to view this page.", 'danger')
        return redirect(url_for('teams.my_team', user_team=team))
    else:
        # get relevant post from the db
        post = Post.query.get_or_404(post_id)
        return render_template('post_page.html', title=post.title,
            post=post)


@posts.route('/post/delete/<int:post_id>')
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    # only post author can delete a post, check that this is the case
    if post.author != current_user:
        flash("You don't have permission to do this!", 'danger')
        return redirect(url_for('posts.post_page', team=post.team, post_id=post.id))
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('teams.team_posts', team=post.team))


@posts.route('/<string:team>/posts/new', methods=['GET', 'POST'])
@login_required
def add_new_post(team):
    # posts pages are on a per-team basis eg Team1 cannot view posts of Team2
    # check that the current user's team is the same as the team associated
    # with the posts
    if current_user.team != team:
        flash("You must be a player on this team to view this page.", 'danger')
        return redirect(url_for('teams.my_team', user_team=team))
    else:
        form = PostForm()
        if form.validate_on_submit():
            post = Post(title=form.title.data,
                    content=form.content.data,
                    date_posted=datetime.now(),
                    team=current_user.team,
                    author=current_user)
            db.session.add(post)
            db.session.commit()
            # allows captain to send the post as an email to all team players
            # (logic to check user is a captain is handled in the HTML templating)
            if form.send_email.data:
                send_post_email(post)
            return redirect(url_for('teams.team_posts', team=team))
    return render_template('new_post.html', title=f'New {team} Post', form=form)


def send_post_email(post):
    with mail.connect() as conn:
        # get all users for this team
        users = User.query.filter_by(team=post.team).all()
        for user in users:
            message = render_template('post_email.html',
            post=post)
            subject = f'New Post In {post.team}'
            sender = 'noreply@demo.com'
            msg = Message(recipients=[user.email],
            sender=sender,
            subject=subject,
            html=message)
            conn.send(msg)

FlaskApp/teams/routes.py
from flask import render_template, redirect, url_for, flash, Blueprint
from FlaskApp import db
from FlaskApp.models import User, Match, Team, Post
from FlaskApp.teams.forms import AddTeam
from flask_login import current_user, login_required
from sqlalchemy import desc


teams = Blueprint('teams', __name__)


@teams.route('/add-team', methods=['POST', 'GET'])
@login_required
def add_team():
    # only league admins and reps can add a new team
    if current_user.admin_level not in ['Admin', 'Rep']:
        flash("You don't have permission to view this page!", 'danger')
        return redirect(url_for('main.home'))
    form = AddTeam()
    if form.validate_on_submit():
        new_team = Team(name=form.name.data)
        db.session.add(new_team)
        db.session.commit()
        flash(f"{form.name.data} added!", 'success')
        return redirect(url_for('main.dashboard'))
    return render_template('add_team.html', title='Add New Team', form=form)


@teams.route('/<string:user_team>')
@login_required
def my_team(user_team):
    # get team details to display on page
    players = User.query.filter_by(team=user_team).all()
    team = Team.query.filter_by(name=user_team).first()
    return render_template('team_details.html', title=user_team, players=players,
        team=team)


@teams.route('/<string:team>/posts')
@login_required
def team_posts(team):
    # posts are restricted on a per team basis. Check that current user's
    # team is the same as the team associated with posts being queried
    if current_user.team != team:
        flash("You must be a player on this team to view this page.", 'danger')
        return redirect(url_for('teams.my_team', user_team=team))
    else:
        # get posts from db and order by descending date (newest first)
        posts = Post.query.filter_by(team=team).order_by(desc(Post.date_posted)).all()
        return render_template('team_posts.html', title=f'{team} Posts',
            team=team, posts=posts)


@teams.route('/<string:team>/matches')
@login_required
def team_matches(team):
    # admins and reps can view team matches, but otherwise restricted
    # to users belonging to the team being queried
    # first check if the user is not an admin or a rep
    if current_user.admin_level not in ['Admin', 'Rep']:
        # if the current user does not belong to team being queried, deny access
        if current_user.team != team:
            flash("You must be a player on this team to view this page", 'danger')
            return redirect(url_for('teams.my_team', user_team=team))
        else:
            # if user is admin, rep or player for team being queried
            # get all matches where the user's team is playing at home or away
            matches = Match.query.filter((Match.home_team==team) | \
                (Match.away_team==team)).order_by(Match.date).all()
            return render_template('team_matches.html',
                    title=f'{team} Matches',
                    matches=matches, team=team)

FlaskApp/users/routes.py
from flask import (render_template, redirect, url_for, flash, request,
    Blueprint, current_app)
from FlaskApp import db, bcrypt, mail
from FlaskApp.models import User, PendingUser, Team, Post
from FlaskApp.users.forms import (AddPlayerRequest, LoginForm,
    AddPlayer, UpdateAccountForm, RequestResetForm, ResetPasswordForm,
    ChangePassword)
from flask_login import login_user, logout_user, current_user, login_required
import secrets
from PIL import Image
import os
from flask_mail import Message


users = Blueprint('users', __name__)


@users.route('/register-player', methods=['POST', 'GET'])
@login_required
def register_player():
    # only team captains can add new players to their team
    if current_user.player_status == 'Captain':
        form = AddPlayerRequest()
        if form.validate_on_submit():
            # generate a random hashed password for the new user
            hashed_password = bcrypt.generate_password_hash(secrets.token_hex(8)).decode('utf-8')
            # new users must be confirmed by an admin or a rep. New users
            # therefore adding to a PendingUser db whilst awaiting approval
            user = PendingUser(name=form.name.data,
                    email=form.email.data,
                    team=current_user.team,
                    password=hashed_password,
                    address_1=form.address_1.data,
                    address_2=form.address_2.data,
                    postcode=form.postcode.data,
                    association_id=form.association_id.data)
            db.session.add(user)
            db.session.commit()
            flash(f'{form.name.data} has been submitted for approval', 'success')
            return redirect(url_for('main.dashboard'))
    else:
        flash("You don't have permission to view this page!", 'danger')
        return redirect(url_for('main.home'))
    return render_template('register_player.html', title='Register New Player',
        form=form)


@users.route('/admin/users', methods=['POST', 'GET'])
@login_required
def users_list():
    if current_user.admin_level not in ['Admin', 'Rep']:
        flash("You don't have permission to view this page!", 'danger')
        return redirect(url_for('main.home'))
    # list all users for admin viewing and actions
    pending_users = PendingUser.query.all()
    approved_users = User.query.all()
    return render_template('users_list.html', title='All Users',
        pending_users=pending_users, approved_users=approved_users)


@users.route('/admin/add-player', methods=['POST', 'GET'])
@login_required
def admin_add_player():
    # admin/reps can add players to any team, with any level of permissions
    # for simplicity, route is therefore handled differently to captain functionality
    if current_user.admin_level not in ['Admin', 'Rep']:
        flash("You don't have permission to view this page!", 'danger')
        return redirect(url_for('main.home'))
    form = AddPlayer()
    # get list of teams in db for admin/rep to assign new player to
    form.team.choices = [(a.name, a.name) for a in Team.query.order_by(Team.name)]
    if form.validate_on_submit():
        # generate random hashed password
        hashed_password = bcrypt.generate_password_hash(secrets.token_hex(8)).decode('utf-8')
        user = User(name=form.name.data,
                email=form.email.data,
                password=hashed_password,
                team=form.team.data,
                player_status=form.player_status.data,
                admin_level=form.admin_level.data,
                address_1=form.address_1.data,
                address_2=form.address_2.data,
                postcode=form.postcode.data,
                association_id=form.association_id.data)
        db.session.add(user)
        db.session.commit()
        # get new user's email to send them details about their account
        user_email = User.query.filter_by(email=form.email.data).first()
        user_approved_email(user_email)
        flash(f'{form.name.data} has been added to {form.team.data}', 'success')
        return redirect(url_for('main.dashboard'))
    return render_template('admin_new_player.html', title='Add New Player', form=form)


def user_approved_email(user):
    token = user.get_reset_token()
    msg = Message('Netball Registration Approved',
        sender='noreply@demo.com',
        recipients=[user.email])
    # _external=True argument is used to generate an absolute URL, instead of relative
    msg.body = f'''Your registration with {user.team} has been approved. \n \n
    Please visit the following link to set your password: \n \n
{url_for('users.reset_token', token=token, _external=True)} \n \n
If you did not make this request, then simply ignore this email and no changes will be made.
    '''
    mail.send(msg)


@users.route('/delete/<string:user_email>', methods=['POST'])
@login_required
def delete_user(user_email):
    # only admins and reps can delete a user
    if current_user.admin_level not in ['Admin', 'Rep']:
        flash("You don't have permission to view this page!", 'danger')
        return redirect(url_for('main.home'))
    # get both pending users and approved users from db
    pending_email = PendingUser.query.filter_by(email=user_email).first()
    approved_email = User.query.filter_by(email=user_email).first()
    # handle deletion logic depending on whether deletion refers to pending
    # user or approved user
    if pending_email:
        db.session.delete(pending_email)
        db.session.commit()
        flash('User deleted!', 'info')
    elif approved_email:
        # bug prevented user from being deleted if they have posts.
        # below fix gets all posts associated with the user, deletes them
        # first (if they exist), and then attempts to delete user
        posts = Post.query.filter_by(user_id=approved_email.id).all()
        if posts:
            for post in posts:
                db.session.delete(post)
        db.session.delete(approved_email)
        db.session.commit()
        flash('User deleted!', 'info')
    else:
        flash('Unable to delete user!', 'info')
    return redirect(url_for('users.users_list'))


@users.route('/approve/<string:user_email>', methods=['POST'])
@login_required
def approve_user(user_email):
    # only admins and reps can approve new users
    if current_user.admin_level not in ['Admin', 'Rep']:
        flash("You don't have permission to view this page!", 'danger')
        return redirect(url_for('main.home'))
    pending_user = PendingUser.query.filter_by(email=user_email).first()
    if pending_user:
        # once pending user has been approved, transfer their data from
        # PendingUser db table, to User db table
        user = User(name=pending_user.name,
                email=pending_user.email,
                password=pending_user.password,
                team=pending_user.team,
                player_status='Approved Player',
                admin_level='User',
                address_1=pending_user.address_1,
                address_2=pending_user.address_2,
                postcode=pending_user.postcode,
                approved_by=current_user.name,
                association_id=pending_user.association_id)
        # add to User db table and remove from PendingUser db table
        db.session.add(user)
        db.session.delete(pending_user)
        db.session.commit()
        # get new user details and email them about their account
        new_id = User.query.filter_by(email=user.email).first()
        user_approved_email(new_id)
        flash(f'{pending_user.name} added to {pending_user.team}!', 'success')
    else:
        flash('Unable to delete user!', 'info')
    return redirect(url_for('users.users_list'))


@users.route('/account/<int:user_id>/<string:user>', methods=['GET', 'POST'])
@login_required
def account(user_id, user):
    # current user is same as user being queried, give the option of
    # updating their account
    if user_id == current_user.id:
        form = UpdateAccountForm()
        if form.validate_on_submit():
            if form.picture.data:
                # if they change their profile picture, run function to resize,
                # reformat etc
                picture_file = save_picture(form.picture.data)
                current_user.profile_pic = picture_file
            current_user.email = form.email.data
            current_user.address_1 = form.address_1.data
            current_user.address_2 = form.address_2.data
            current_user.postcode = form.postcode.data
            current_user.association_id = form.association_id.data
            db.session.commit()
            flash('Account updated!', 'success')
            return redirect(url_for('users.account', user_id=current_user.id, user=current_user.name))
        # if request method is GET, prepopulate form fields with the
        # current user data
        elif request.method == 'GET':
            form.email.data = current_user.email
            form.address_1.data = current_user.address_1
            form.address_2.data = current_user.address_2
            form.postcode.data = current_user.postcode
            form.association_id.data = current_user.association_id
        # get user's profile picture for HTML rendering
        image_file = url_for('static', filename='profile_pics/' + current_user.profile_pic)
        return render_template('account.html', title='My Account',
            image_file=image_file, form=form)
    else:
        player = User.query.filter_by(id=user_id).first()
        image_file = url_for('static', filename='profile_pics/' + player.profile_pic)
        return render_template('user_account.html', title=player.name,
            player=player, image_file=image_file)


def save_picture(form_picture):
    # generate a randon string for file name
    random_hex = secrets.token_hex(8)
    # remove name of original file, make a note of the extension (jpeg, png)

FlaskApp/templates/add_team.html
{% extends 'layout.html' %}
{% block content %}

    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Enter New Team Details</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}

                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-md is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-md") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock content %}

FlaskApp/templates/change_password.html
{% extends 'layout.html' %}

{% block content %}

    <div class="content-section">
        <div class="media">
            <img src="{{ image_file }}" alt="" class="rounded-circle account-img">
            <div class="media-body">
                <h4 class="account-heading"> {{ current_user.name }} </h4>
                <p class="text-secondary"> {{ current_user.email }} </p>
            </div>
        </div>
    </div>

    <div class="content-section p-4">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Your Password</legend>

                <div class="form-group">
                    {{ form.new_password.label(class="form-control-label") }}

                    {% if form.new_password.errors %}
                        {{ form.new_password(class="form-control form-control-md is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.new_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.new_password(class="form-control form-control-md") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.confirm_new.label(class="form-control-label") }}

                    {% if form.confirm_new.errors %}
                        {{ form.confirm_new(class="form-control form-control-md is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_new.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_new(class="form-control form-control-md") }}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock content %}

FlaskApp/templates/home.html
{% extends 'layout.html' %}
{% block content %}

    <div class="text-center">
        <div class="content-section">
            <div class="border-bottom mb-3">
                <div class="container">
                    <div class="d-flex flex-wrap text-center justify-content-center">
                        <div class="m-2">
                            <h3>Recent Matches</h3>
                        </div>
                        <div class="m-2">
                            <h3>
                                <a href="{{url_for('matches.previous_matches')}}">
                                <button class="btn branding">
                                All Previous Matches
                                </button>
                            </a>
                            </h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row justify-content-around">
                    {% for match in prev_matches[:2] %}
                        <div class="col-sm m-3 content-section">
                            <h4 class="m-1"><a href="{{url_for('matches.match_page', match_id=match.id)}}">
                            {{ match.home_team }} vs {{ match.away_team }}</a></h4>
                            {% if match.time %}
                            <p class=m-2> at {{ match.time.strftime('%H:%M') }} on {{ match.date.strftime('%d/%m/%Y') }}</p>
                            {% endif %}
                            <p class="m-1"> where: {{ match.location }}</p>
                            {% if match.home_approved and match.away_approved %}
                                <p class="m-1"> Score: {{ match.home_score }} - {{ match.away_score }}</p>
                            {% else %}
                                <p class="m-1"> Score: Match not finished</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    {% for match in prev_matches[2:] %}
                        <div class="col-sm m-3 content-section">
                            <h4 class="m-1"><a href="{{url_for('matches.match_page', match_id=match.id)}}">
                            {{ match.home_team }} vs {{ match.away_team }}</a></h4>
                            {% if match.time %}
                            <p class=m-2> at {{ match.time.strftime('%H:%M') }} on {{ match.date.strftime('%d/%m/%Y') }}</p>
                            {% endif %}
                            <p class="m-1"> where: {{ match.location }}</p>
                            {% if match.home_approved and match.away_approved %}
                                <p class="m-1"> Score: {{ match.home_score }} - {{ match.away_score }}</p>
                            {% else %}
                                <p class="m-1"> Score: Match not finished</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="content-section">
            <div class="border-bottom mb-3">
                <div class="container">
                    <div class="d-flex flex-wrap text-center justify-content-center">
                        <div class="m-2">
                            <h3>Upcoming Matches</h3>
                        </div>
                        <div class="m-2">
                            <h3>
                                <a href="{{url_for('matches.upcoming_matches')}}">
                                <button class="btn branding">
                                All Upcoming Matches
                                </button>
                            </a>
                            </h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    {% for match in next_matches[:2] %}
                        <div class="col-sm m-3 content-section">
                            <h4 class="m-1"><a href="{{url_for('matches.match_page', match_id=match.id)}}">
                            {{ match.home_team }} vs {{ match.away_team }}</a></h4>
                            {% if match.time %}
                            <p class=m-2> at {{ match.time.strftime('%H:%M') }} on {{ match.date.strftime('%d/%m/%Y') }}</p>
                            {% endif %}
                            <p class="m-1"> where: {{ match.location }}</p>
                            {% if match.home_approved and match.away_approved %}
                                <p class="m-1"> Score: {{ match.home_score }} - {{ match.away_score }}</p>
                            {% else %}
                                <p class="m-1"> Score: Match not finished</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    {% for match in next_matches[2:] %}
                        <div class="col-sm m-3 content-section">
                            <h4 class="m-1"><a href="{{url_for('matches.match_page', match_id=match.id)}}">
                            {{ match.home_team }} vs {{ match.away_team }}</a></h4>
                            {% if match.time %}
                            <p class=m-2> at {{ match.time.strftime('%H:%M') }} on {{ match.date.strftime('%d/%m/%Y') }}</p>
                            {% endif %}
                            <p class="m-1"> where: {{ match.location }}</p>
                            {% if match.home_approved and match.away_approved %}
                                <p class="m-1"> Score: {{ match.home_score }} - {{ match.away_score }}</p>
                            {% else %}
                                <p class="m-1"> Score: Match not finished</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

FlaskApp/templates/league_info.html
{% extends 'layout.html' %}

{% block content %}

    <table class="table table-bordered table-hover text-center">
        <thead class="thead-dark">
            <tr>
                <th>Team</th>
                <th>Points</th>
                <th>Won</th>
                <th>Lost</th>
                <th>Drawn</th>
            </tr>
        </thead>
        {% for team in teams %}
            <tr>
                <th> <a href="{{url_for('teams.my_team', user_team=team.name)}}">{{team.name}}</a> </th>
                <th> {{team.points}} </th>
                <th> {{team.matches_won}} </th>
                <th> {{team.matches_lose}} </th>
                <th> {{team.matches_drawn}} </th>
            </tr>
        {% endfor %}
    </table>

{% endblock content %}

FlaskApp/templates/post_email.html
<h3> {{ post.author.name }} has made a new post in {{ post.team }}! </h3>

<h2> {{ post.title }} </h2>

<h4> {{ post.content[:120] }}... </h4>

<h3>
  <a href="{{ url_for('posts.team_posts', team=post.team, _external=True) }}">
    Login to your account
  </a> to see the post!
</h3>

FlaskApp/templates/post_page.html
{% extends 'layout.html' %}

{% block content %}

  <article class="media content-section">
    <img src="{{ url_for('static', filename='profile_pics/' + post.author.profile_pic) }}"
    alt="" class="rounded-circle article-img">
    <div class="media-body">
      <div class="article-metadata">
        by <a class="mr-2" href="{{url_for('users.account', user_id=post.author.id, user=post.author.name)}}">{{ post.author.name }}</a>
        <small class="text-muted"> On {{ post.date_posted.strftime('%d-%m-%Y') }}
            at {{ post.date_posted.strftime('%H:%M') }}
        </small>
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>

         {% if current_user == post.author %}
        <a href="{{url_for('posts.delete_post', post_id=post.id)}}">
            <button class="btn btn-danger mt-5">
                Delete Post
            </button>
        </a>
        {% endif %}

    </div>
  </article>

{% endblock content %}

FlaskApp/templates/reset_request.html
{% extends 'layout.html' %}
{% block content %}

    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-md is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-md") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock content %}

FlaskApp/templates/users_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="text-center">
        <h3>Pending Users</h3>
        {% if pending_users %}
            <div class="d-flex justify-content-center flex-wrap">
                {% for pending_user in pending_users %}
                    <div class="content-section m-3">
                        <p> {{ pending_user.admin_level }}</p>
                        <p> {{ pending_user.name }}: {{ pending_user.email }} </p>
                        <p> {{ pending_user.team }}: {{ pending_user.player_status }} </p>
                        <form action="{{url_for('users.delete_user', user_email=pending_user.email)}}"
                        method="POST" class="form-check-inline">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                        <form action="{{url_for('users.approve_user', user_email=pending_user.email)}}"
                        method="POST" class="form-check-inline">
                            <input type="submit" class="btn btn-success" value="Approve">
                        </form>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h5 class="mt-3 mb-5">No users pending approval</h5>
        {% endif %}
    </div>

    <div class="text-center">
        <h3>Approved Users</h3>
        <div class="d-flex justify-content-center flex-wrap">
            {% for approved_user in approved_users %}
                <div class="content-section m-3">
                    <p> {{ approved_user.admin_level }} </p>
                    <p> {{ approved_user.name }}: {{ approved_user.email }} </p>
                    <p> {{ approved_user.team }}: {{ approved_user.player_status }} </p>
                    <form action="{{url_for('users.delete_user', user_email=approved_user.email)}}" method="POST">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}